server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://springboot-db.cj0bstca4lvc.ap-northeast-2.rds.amazonaws.com:3306/test_finalproject_dontbeweak
    username: hyerim
    password: hyerim12

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

cos:
  key: cos1234

secret:
  key: thwjd2