# logging-deploy.yml

name: Spring Boot & Gradle CI/CD 

# 이 workflow 가 언제 실행될건지 트리거를 지정.
# 특정 브랜치가 push 되는 경우, 
# Pull Request 가 생성될 경우, 또는 crontab 문법으로 스케줄링을 걸 수도 있습니다.
# workflow_dispatch는 수동으로 해당 workflow를 실행시키겠다는 의미.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# workflow 는 하나 혹은 그 이상의 job 을 가질 수 있고
# 각 job 은 여러 step 에 따라 단계를 나눌 수 있습니다.
# runs-on 해당 workflow를 어떤 os 환경에서 실행할 것인지 지정.
# checkout 은 GITHUB이 제공하는 워크스페이스 (이 workflow 를 실행하는 공간) 에서
# 내 저장소가 위치한 곳으로 이동한다고 생각하면 된다.
# 이후는 JAVA를 셋업하고 gradlew에 실행 권한을 준 뒤 build하는 과정.
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      # 임의 추가. gradle wrapper없이 바로 빌드하면 경로 문제 때문인지 오류 남.
      - name: gradle wrapper
        run: gradle wrapper
      
      # Build
      - name: Build with Gradle
        run: gradle clean build
        
      # 전송할 파일을 담을 디렉토리 생성
      - name: Make Directory for deliver
        run: mkdir deploy

      # Jar 파일 Copy
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy/

      # 압축파일 형태로 전달
      - name: Make zip file
        run: zip -r -qq -j ./springboot-intro-build.zip ./deploy
      
      # S3로 전달하는 과정에서 .zip 파일 못 찾는 오류. 파일 찾기
      # The user-provided path  ./springboot-intro-build.zip does not exist.
      # Error: Process completed with exit code 255.
      # - name: Find /build
      #   run: ls -la         # ls 디렉토리 목록보기, -l 지정한 디렉토리 내용을 자세히 출력 -a .을 포함한 경로안의 모든 파일과 디렉토리 표시
        
      # pwd: Print Working Directory. 현재 디렉토리 경로를 절대 경로로 표시
      # - name: Print Working Directory
      #   run: pwd

      # S3 Bucket으로 copy
      - name: Deliver to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          --acl private \ /home/runner/work/DontBeWeak-BE/DontBeWeak-BE/springboot-intro-build.zip s3://springboot-intro-build/
